import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const space = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "WebPtoJPG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" class="dark">
      <body className={`${space.className} bg-slate-50 dark:bg-slate-800`}>
        {children}
      </body>
    </html>
  );
}
